config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :new,
  controllers: {
    # sessions: 'users/sessions',
    # registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
    get 'new' => 'devise/sessions#new'
    post 'create' => 'devise/sessions#create'
  end

  root to: "items#index"

  resources :sign_ups, only: [:index] do
    collection do
      get :registration  # 登録情報の一部を入力してもらう
      post :registration, to: 'signups#step1_validates'  #step1で入力したデータのバリデーションチャックをする(詳しくはコントローラーで説明) render後にリロードしてもエラーが出ないようにget'step1'とURLは同じに設定する
      get :sms_confirmation  # 残りの登録情報を入力してもらう
      post :sms_confirmation, to: 'signups#create' # 入力した情報すべてを保存 こっちもrenderするなら揃える
    end
  end

  resources :items do
    collection do
      get :buy
      get :buy1
    end
    member do
      get :details
      get :address
      get :buy
      get :confimation
      post :confimation
      post :buy1
    end
  end    
  resources :pays, only: [:new]
  resources :users, only: [:new, :create, :show, :edit, :destroy] do
    collection do
      get :login
    end
    member do
      get :identification
      get :logout
      get :profile
      post :profile
      get :selling
      get :saling
      get :sold
      get :selling_items
      get :card_info
      get :zoom
    end
  end
  resources :signup, only: [:create] do
    collection do
      get :registration
      get :sms_confirmation
      post :sms_confirmation
      get :address
      post :address
      get :card
      post :card
      get :complete
      post :complete
      get :logout
    end
    member do
      get :identification
      get :saling
      get :selling
      get :sold
    end
  end

  resources :cards, only: [:index, :create, :new] do
    member do 
      get :buy
      get :confimation
      post :confimation
      get :completed
      # post 'confimation/:id'=> 'cards#confimation', as: 'confimation' #httpメソッドはpostなので注意
      # get  'completed'=>  'cards#completed', as: 'completed'
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :save_to_session, only: :address
  def create
    @user = User.new(
      nickname: session[:nickname],
      family_name: session[:family_name],
      last_name: session[:last_name],
      password: session[:password_confirmation],
      email: session[:email],
      j_family_name: session[:j_family_name],
      j_last_name: session[:j_last_name],
      birthday_day_id: session[:birthday_day_id],
      birthday_year_id: session[:birthday_year_id],
      birthday_month_id: session[:birthday_month_id],
      phone_number: session[:phone_number]
    )
    @user.build_address(session[:address_params])
    @user.build_pay(user_params[:pay_attributes])
    begin 
      @user.save!
      puts "保存に成功しました"
      session[:id] = @user.id
      redirect_to complete_signup_index_path
    rescue ActiveRecord::RecordInvalid => e
      puts e
      puts "保存に失敗しました"
    end
  end  

  def registration
    @user = User.new
  end

  def save_to_session
    
    session[:phone_number] = user_params[:phone_number]
    
    @user = User.new(
      nickname: session[:nickname],
      family_name: session[:family_name],
      last_name: session[:last_name],
      password: session[:password_confirmation],
      email: session[:email],
      j_family_name: session[:j_family_name],
      j_last_name: session[:j_last_name],
      birthday_day_id: session[:birthday_day_id],
      birthday_year_id: session[:birthday_year_id],
      birthday_month_id: session[:birthday_month_id],
      phone_number: session[:phone_number]
    )
    render '/signup/registration/' unless @user.valid?
  end

  def sms_confirmation
    
    
    session[:nickname] = user_params[:nickname]
    session[:family_name] = user_params[:family_name]
    session[:last_name] = user_params[:last_name]
    session[:password_confirmation] = user_params[:password]
    session[:email] = user_params[:email]
    session[:j_family_name] = user_params[:j_family_name]
    session[:j_last_name] = user_params[:j_last_name]
    session[:birthday_year_id] = user_params[:birthday_year_id]
    session[:birthday_month_id] = user_params[:birthday_month_id]
    session[:birthday_day_id] = user_params[:birthday_day_id]
    @user = User.new
  end

  def address
    @user = User.new
    @user.build_address
  end

  def card
    session[:address_params] = user_params[:address_attributes]
    @user = User.new
    @user.build_pay
  end

  def complete
    sign_in User.find(session[:id]) unless user_signed_in?
  end

  private

  def user_params
    params.require(:user).permit(
      :email, 
      :nickname, 
      :password,
      :family_name, 
      :last_name, 
      :j_family_name, 
      :j_last_name, 
      :birthday_year_id, 
      :birthday_month_id, 
      :birthday_day_id, 
      :phone_number,

      address_attributes: 
      [:id,
      :family_name, 
      :last_name, 
      :postal_code, 
      :prefecture_id, 
      :city, 
      :banti, 
      :building_name, 
      :phone_number
      ],

      pay_attributes:
      [:id,
      :card_number, 
      :deadline_month_id,
      :deadline_year_id, 
      :security_code
      ]
    )
  end
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/address.html.haml
.contents
  .header
    .fmarket
      .fmarket__box
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg",class: "logo"
    .clearfix_a
      .progress-bar1a
        .progress-bar1a__0
          会員情報
        .progress-bar1a__x
      .progress-bar2a
        電話番号認証
        .progress-bar2a__x
      .progress-bar3a
        お届け先住所入力
        .progress-bar3a__x
      .progress-bar4a
        支払い方法
        .progress-bar4a__x
      .progress-bar5a
        .progress-bar5a__0
          完了
        .progress-bar5a__x
  .single
  = form_for @user,url: card_signup_index_path , method: :get, html:{class: 'single'} do |f|
    = f.fields_for :address do |a|
      .single__head
        %h1
          お届け先住所入力
      .single-box
        .single-box15
          %li
            お名前(全角)
          .single-box16
            必須
          = a.text_field :family_name, placeholder: "例) 山田", type: "text", class: "input-default"
          = a.text_field :last_name, placeholder: "例) 彩", type: "text", class: "input-default2"
        .single-box15
          %li
            お名前カナ(全角)
          .single-box17
            必須
          = a.text_field :family_name, placeholder: "例) ヤマダ", type: "text", class: "input-default"
          = a.text_field :last_name, placeholder: "例) アヤ", type: "text",class: "input-default2"
        .single-box18
          %li
            郵便番号
          .single-box19
            必須
          = a.text_field :postal_code, placeholder: "例) 123-4567", type: "text",class: "input-default"
        .single-box18
          %li
            都道府県
          .single-box19
            必須
          .areaselect
            = a.collection_select :prefecture_id, Prefecture.all, :id, :name
            .ic
              = fa_icon "chevron-down"
        .single-box18
          %li
            市区町村
          .single-box19
            必須
          = a.text_field :city, placeholder: "例) 横浜市緑区", type: "text",class: "input-default"
        .single-box20
          %li
            番地
          .single-box21
            必須
          = a.text_field :banti, placeholder: "例) 青山1-1-1", type: "text",class: "input-default"
        .single-box22
          %li
            建物名
          .single-box23
            任意
          = a.text_field :building_name, placeholder: "例) 柳ビル103", type: "text",class: "input-default"
        .single-box20
          %li
            電話
          .single-box25
            任意
          = a.text_field :phone_number, placeholder: "例) 09012345678", type: "text",class: "input-default"
        .button_box2
          = f.submit "次へ進む", class: "btn-default btn-red"
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "フリマ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari

app/views/signup/card.html.haml
.contents
  .header
    .fmarket
      .fmarket__box
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg",class: "logo"
    .clearfix_c
      .progress-bar1c
        .progress-bar1c__0
          会員情報
        .progress-bar1c__x
      .progress-bar2c
        電話番号認証
        .progress-bar2c__x
      .progress-bar3c
        お届け先住所入力
        .progress-bar3c__x
      .progress-bar4c
        支払い方法
        .progress-bar4c__x
      .progress-bar5c
        .progress-bar5c__0
          完了
        .progress-bar5c__x
  .single
  = form_for @user,url: signup_index_path , method: :post, html:{class: 'single'} do |f|
    = f.fields_for :pay do |c|
      .single__head
        %h1
          支払い方法
      .single-box
        .single-box24
          %li
            カード番号
          .single-box25
            必須
          = c.text_field :card_number, placeholder: "半角数字のみ", type: "text", class: "input-default"
        .ic2
          .card1
          .card2
          .card3
          .card4
          .card5
          .card6
          .card7
        .single-box26
          %li
            有効期限
          .single-box27
            必須
          = c.collection_select :deadline_month_id, DeadlineMonth.all, :id, :name
          = c.collection_select :deadline_year_id, DeadlineYear.all, :id, :name
          .ic3
            = fa_icon "chevron-down"
          .ic4
            = fa_icon "chevron-down"
        .single-box28
          %li
            セキュリティコード
          .single-box29
            必須
          = c.text_field :security_code, placeholder: "カード背面4桁もしくは3桁の番号", type: "text", class: "input-default"
        .message4
          %p
            %a{:href => "/jp/help_center/article/244/", target: "_blank"}> カード裏面の番号とは？
        .button_box3
          = f.submit "次へ進む", class: "btn-default btn-red"
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "フリマ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari

app/views/signup/complete.html.haml
.contents
  .header
    .fmarket
      .fmarket__box
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg",class: "logo"
    .clearfix_x
      .progress-bar1x
        .a
          会員情報
        .progress-bar1x__x
      .progress-bar2x
        電話番号認証
        .progress-bar2x__x
      .progress-bar3x
        お届け先住所入力
        .progress-bar3x__x
      .progress-bar4x
        支払い方法
        .progress-bar4x__x
      .progress-bar5x
        .bbb
          完了
        .progress-bar5x__x
  .single0
    .single0__head
      %h1
        会員登録完了
    .single-box
      .single-box30
        %p
          ありがとうございます。
        %p
          会員登録が完了しました。
    .button_box4
      = link_to root_path do
        %button.btn-default.btn-red
          フリーマーケットをはじめる
    .bottomlinks
      %h1
        ＼　スマホでかんたんフリマアプリ　／
      %h2
        今すぐ無料ダウンロード！
      =link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
        = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg', class: "icon-image", width: "170", height: "50"
      =link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja" do
        = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg', class: "icon-image", width: "170", height: "50"
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "フリマ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari

app/views/signup/registration.html.haml
.contents
  .header
    .fmarket
      .fmarket__box
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg",class: "logo"
    .clearfix
      .progress-bar1
        .progress-bar1__0
          会員情報
        .progress-bar1__x
      .progress-bar2
        電話番号認証
        .progress-bar2__x
      .progress-bar3
        お届け先住所入力
        .progress-bar3__x
      .progress-bar4
        支払い方法
        .progress-bar4__x
      .progress-bar5
        .progress-bar5__0
          完了
        .progress-bar5__x
  .single
  = form_for @user,url: sms_confirmation_signup_index_path , method: :get, html:{class: 'single'} do |f|
    .single__head
      %h1
        会員情報入力
    .single-box
      - if @user.errors.full_messages != []
        = @user.errors.full_messages
      .single-box2
        %li
          ニックネーム
        .single-box3
          必須
        = f.text_field :nickname, placeholder: "例) メルカリ太郎", type: "text", class: "input-default"
      .single-box4
        %li
          メールアドレス
        .single-box5
          必須
        = f.text_field :email, placeholder: "PC・携帯どちらでも可", type: "email",class: "input-default"
      .single-box6
        %li
          パスワード
        .single-box7
          必須
        = f.text_field :password, placeholder: "7文字以上", type: "password",class: "input-defaultx"
        %a.passbox
        %label
          %input.checkbox-default{type: "checkbox", id:"password-check"}/
          パスワードを表示する
      .single-box8
        %h2
          本人確認
        .option
          %p
            安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
      .single-box9
        %li
          お名前(全角)
        .single-box10
          必須
        = f.text_field :family_name, placeholder: "例) 山田", type: "text", class: "input-default"
        = f.text_field :last_name, placeholder: "例) 彩", type: "text",class: "input-default"
      .single-box9
        %li
          お名前カナ(全角)
        .single-box11
          必須
        = f.text_field :j_family_name, placeholder: "例) ヤマダ", type: "text",class: "input-default"
        = f.text_field :j_last_name, placeholder: "例) アヤ", type: "text",class: "input-default"
      .single-box13
        %li
          生年月日
        .single-box14
          必須
        .icons
          = fa_icon "chevron-down"
          %i= fa_icon "chevron-down"
          %i= fa_icon "chevron-down"
        = f.collection_select :birthday_year_id, BirthdayYear.all, :id, :name
        = f.collection_select :birthday_month_id, BirthdayMonth.all, :id, :name
        = f.collection_select :birthday_day_id, BirthdayDay.all, :id, :name
        .caution
          %p
            ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
      .the_box
        %iframe{frameborder: "0", name: "a-x6czxoic852l", role: "presentation", sandbox: "allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox", scrolling: "no", src: "https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfZGCYTAAAAAHoK-s7Lg5OdYg5Fq4susvALmZoc&co=aHR0cHM6Ly93d3cubWVyY2FyaS5jb206NDQz&hl=ja&v=75nbHAdFrusJCwoMVGTXoHoM&size=normal&cb=8by6abyui13", }
        #g-recaptcha-response.g-recaptcha-response{name: "g-recaptcha-response",}
      .caution2
        「次へ進む」のボタンを押すことにより、
        %a{href: "/jp/tos_list/", target: "_blank"}> 利用規約
        に同意したものとみなします
      .button_box
        = f.submit "次へ進む", class: "btn-default btn-red"
      .last_text
        %p
          %a{href: "/jp/help_center/article/423/", target: "_blank"}> 本人情報の登録について
          = fa_icon "chevron-right"
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "フリマ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari

app/views/signup/sms_confirmation.html.haml
.contents
  .header
    .fmarket
      .fmarket__box
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg",class: "logo"
    .clearfix_s
      .progress-bar1s
        .progress-bar1s__0
          会員情報
        .progress-bar1s__x
      .progress-bar2s
        電話番号認証
        .progress-bar2s__x
      .progress-bar3s
        お届け先住所入力
        .progress-bar3s__x
      .progress-bar4s
        支払い方法
        .progress-bar4s__x
      .progress-bar5s
        .bbb
          完了
        .progress-bar5s__x
  .singles
  = form_with model: @user, local: true, url: address_signup_index_path, class: 'singles' do |f|
    .singles__head
      %h1
        電話番号の確認
    .singles-box
      .singles-box2
        %li
          携帯電話の番号
        = f.text_field :phone_number, placeholder: "携帯電話の番号を入力", type: "text", class: "input-default"
        .message1
          本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
      .button_box
        = f.submit "SMSを送信する",　class: "btn-defaultbtn-red"
        .message2
          ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
      .message3
        %p
          %a{href: "/jp/help_center/article/244/", target: "_blank"}> 電話番号の確認が必要な理由
          = fa_icon "chevron-right"
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "フリマ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari