config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :new,
  controllers: {
    # sessions: 'users/sessions',
    # registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
    get 'new' => 'devise/sessions#new'
    post 'create' => 'devise/sessions#create'
  end

  root to: "items#index"

  resources :sign_ups, only: [:index] do
    collection do
      get :registration  # 登録情報の一部を入力してもらう
      post :registration, to: 'signups#step1_validates'  #step1で入力したデータのバリデーションチャックをする(詳しくはコントローラーで説明) render後にリロードしてもエラーが出ないようにget'step1'とURLは同じに設定する
      get :sms_confirmation  # 残りの登録情報を入力してもらう
      post :sms_confirmation, to: 'signups#create' # 入力した情報すべてを保存 こっちもrenderするなら揃える
    end
  end

  resources :items do
    collection do
      get :buy
      get :buy1
    end
    member do
      get :details
      get :address
      get :buy
      get :confimation
      post :confimation
      post :buy1
    end
  end    
  resources :pays, only: [:new]
  resources :users, only: [:new, :create, :show, :edit, :destroy] do
    collection do
      get :login
    end
    member do
      get :identification
      get :logout
      get :profile
      post :profile
      get :selling
      get :saling
      get :sold
      get :selling_items
      get :card_info
      get :zoom
    end
  end
  resources :signup, only: [:create] do
    collection do
      get :registration
      get :sms_confirmation
      post :sms_confirmation
      get :address
      post :address
      get :card
      post :card
      get :complete
      post :complete
      get :logout
    end
    member do
      get :identification
      get :saling
      get :selling
      get :sold
    end
  end

  resources :cards, only: [:index, :create, :new] do
    member do 
      get :buy
      get :confimation
      post :confimation
      get :completed
      # post 'confimation/:id'=> 'cards#confimation', as: 'confimation' #httpメソッドはpostなので注意
      # get  'completed'=>  'cards#completed', as: 'completed'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :birthday_year
  belongs_to_active_hash :birthday_month
  belongs_to_active_hash :birthday_day
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :sns_credentials, dependent: :destroy
  has_one :card
  

  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :saling_items, -> {where("buyer_id is NULL")}, foreign_key: "saler_id", class_name: "Item" 
  has_many :selling_items, -> {where("buyer_id is not NULL")}, foreign_key: "saler_id", class_name: "Item"
  has_many :sold_items, -> {where("saler_id is NULL")}, foreign_key: "buyer_id", class_name: "Item"
         
  has_one :address
  has_one :pay
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :pay

  has_many :rates
  has_many :goods
  has_many :items
  has_many :comments
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :saling_items, -> {where("buyer_id is NULL")}, foreign_key: "saler_id", class_name: "Item"
  has_many :selling_items, -> {where("buyer_id is not NULL")}, foreign_key: "saler_id", class_name: "Item"
  has_many :sold_items, -> {where("saler_id is NULL")}, foreign_key: "buyer_id", class_name: "Item"

  validates :birthday_year_id,  presence: :true
  validates :birthday_month_id, presence: :true
  validates :birthday_day_id,   presence: :true
  validates :phone_number,      presence: :true
  validates :nickname,          presence: :true,     length: {maximum: 20 }
  validates :family_name,       presence: :true,     length: {maximum: 35 }
  validates :last_name,         presence: :true,     length: {maximum: 35 }
  validates :j_family_name,     presence: :true,     length: {maximum: 35 }
  validates :j_last_name,       presence: :true,     length: {maximum: 35 }
  validates :family_name, format: {
  with: /\A[一-龥ぁ-ん]/,
  }
  validates :last_name,format: {
  with: /\A[一-龥ぁ-ん]/,
  }
  validates :j_family_name,format: {
  with: /\A[ァ-ヶー－]+\z/,
  }
  validates :j_last_name,format: {
  with: /\A[ァ-ヶー－]+\z/,
  }
  validates :phone_number,format: {
   with: /\A\d{10}\z|\A\d{11}\z/,
  }

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first #firstをつけないとデータが配列で返されて使いたいメソッドが使えなくて困る

    #sns_credentialsが登録されている
    if snscredential.present?
      user = User.where(email: auth.info.email).first

      # userが登録されていない
      unless user.present?
        user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
        )
      end
      sns = snscredential
      #返り値をハッシュにして扱いやすくする  
      #活用例 info = User.find_oauth(auth) 
             #session[:nickname] = info[:user][:nickname]
      { user: user, sns: sns}

    #sns_credentialsが登録されていない
    else
      user = User.where(email: auth.info.email).first


      # userが登録されている
      if user.present?
        sns = SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
        )

        { user: user, sns: sns}

      # userが登録されていない
      else
        user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: uid,
          provider: provider
        )

        { user: user, sns: sns}
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      session[:email] = info[:user][:email]
      session[:nickname] = info[:user][:nickname]
      session[:password_confirmation] = SecureRandom.alphanumeric(30)
      
      #snsでのユーザ登録ではパスワードを入力させないので準備する。
      #今回のバリデーションは英数字のみなのでこっちを採用
      render template: "users/sign_up" 
    end

    # if SnsCredential.find_by(uid: info[:sns][:uid], provider: info[:sns][:provider]).nil?
    #   #ユーザ登録と同時にsns_credentialも登録するために
    #   session[:uid] = info[:sns][:uid]
    #   session[:provider] = info[:sns][:provider]
    # end
  end
  

  def failure
    
    redirect_to root_path and return
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:saling, :selling, :sold]

  def new
  end

  def create
    @user = User.new(
      nickname: session[:nickname], # sessionに保存された値をインスタンスに渡す
      email: session[:email],
      password: session[:password],
      # password_confirmation: session[:password_confirmation],
      last_name: session[:last_name], 
      first_name: session[:first_name], 
      last_name_kana: session[:last_name_kana], 
      first_name_kana: session[:first_name_kana], 
      birthday_year: session[:birthday_year],
      birthday_month: session[:birthday_month],
      birthday_day: session[:birthday_day],
    )
    if @user.save
      # ログインするための情報を保管
      session[:id] = @user.id
      redirect_to complete_users_path
    else
      render '/signup/registration'
    end
  end

  def login
  end

  def show
  end

  def edit
  end

  def zoom
    
  end
  
  def registration
  end

  def profile
  end

  def card_info
  end

  def logout
  end

  def identification
    @birthday1 = current_user.birthday_year.name
    @birthday2 = current_user.birthday_month.name
    @birthday3 = current_user.birthday_day.name
  end

  def saling
    @items = current_user.saling_items
  end

  def selling
    @items = current_user.selling_items
  end

  def sold
    @items = current_user.sold_items
  end

  def selling_items
    @items = Item.where(saler_id: current_user.id)
  end

  private

  def set_user
    user = User.find(params[:id])
  end


end

app/helpers/users/omniauth_callbacks_controller_helper.rb
module Users::OmniauthCallbacksControllerHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/card_info.html.haml
.card-wrapper
  = render 'shared/header-login'
  .indenti-crumbs
    - breadcrumb :card_info
    = render "layouts/breadcrumbs"
  .main-content.clearfix
    .card
      .card__right
        %h2.card__right--title 支払い方法
        .card__right--content
          %p.card-index クレジットカード一覧
          -# .card-button  「カードの登録がないときのビュー」
          -#   .card-button__tag
          -#     = link_to '' , class: 'card-button-link' do
          -#       = fa_icon "credit-card", class: 'card-button-icon'
          -#       %p.card-button-text クレジットカードを追加する
          %ul.cards
            %li.cards__show
              = form_with model: @user, class: 'cards__show--form', local: true do |f|
                = image_tag "mc_vrt_opt_pos_46_1x.png", width: "34", height: "20"
                %p.card-info ************1975
                %p.card-info 10 / 21 
                = f.submit "削除する", class: "card-delete"
            
          .card-link
            = link_to '', class: 'card-link-text' do
              %p.card-link-font 支払い方法について
              = fa_icon "chevron-right", class: 'card-link-icon'
    = render 'shared/sidebar'
  = render 'shared/footer'

.sell-icon
  = link_to "" do
    .red-circle
      %p.text 出品
      = fa_icon 'camera', class: "camera"

app/views/users/logout.html.haml
.topper
  = render "shared/header-login" 
  
.indenti-crumbs
  - breadcrumb :logout
  = render "layouts/breadcrumbs"

.content 
  .logout-mains
    = render "shared/sidebar"
    .my-logout
      .my-logout__bottom
        =link_to destroy_user_session_path, method: :delete, class: "logout-btn" do
          ログアウト



.footer
  = render "shared/footer"

.sell-icon1
  = render "shared/sell-icon"  
  

app/views/users/new.html.haml
.contents
  .header
    .header__box
      = link_to root_path do
        = image_tag "fmarket_logo_red.svg"
  .main
    .main__head
      新規会員登録
    .form
      .form__box
        = link_to registration_signup_index_path do
          .box1
            メールアドレスで登録する
            = fa_icon "envelope", class: "boximage"
        = link_to user_facebook_omniauth_authorize_path, method: :post, class: "box2" do
          Facebookで登録する
          = fa_icon "facebook-square" , class: "boximage2"
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: "box3" do
          Googleで登録する
          .boximage3
            %img{ src: "//www.mercari.com/jp/assets/img/common/common/google.svg"}/
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "フリマ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari

app/views/users/profile.html.haml
.profile-wrapper
  = render 'shared/header-login'
  .indenti-crumbs
    - breadcrumb :profile
    = render "layouts/breadcrumbs"
  .main-content.clearfix
    .profile
      .profile__right
        %h1.profile__right--top プロフィール
        .profile__right--bottom
          = form_with model: @user, class: 'profile-form', local: true do |f|
            .profile-name
              = current_user.nickname
              .profile-image
                = image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgKIFBhPPXWTbAkgXHeVP-T_yJ5IGPxot6pdT0-DSnh3ZJOKtkeg&s", class: "profile-name-image"
              = f.text_field :nickname, class: 'profile-name__input'
            .profile-text
              = f.text_area :introduction, class: 'profile-text__input',  placeholder: '例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪'
              = f.submit '変更する', class: 'profile-text__submit'
    =render 'shared/sidebar'
  = render 'shared/footer'

.sell-icon
  = link_to "" do
    .red-circle
      %p.text 出品
      = fa_icon 'camera', class: "camera"

app/views/users/saling.html.haml
.sale__item.crearfix
  .sale__item--top
    = render "/shared/header-login"
  .sale__item__sidebar
    = render "/shared/sidebar"
  .sale__item--redcircle
    = render "/shared/sell-icon"
    .sale__item__box
      .sale__item__box__main
        出品した商品
      .sale__item__box__sale
        = link_to "出品した商品・出品中", selling_items_user_path, class: "note"
      .sale__item__box__sell
        = link_to "出品した商品・取引中", selling_user_path, class: "note"
      .sale__item__box__sold
        = link_to "出品した商品・売却済み", sold_user_path, class: "note"
      .sale__item__box__list
        .saling
        - if @items.present?
          - @items.each do |item|
            .saling__all
              = item.name
        - else
          .saling__else
            = image_tag "logo_white.svg", height: '120px', width: '120px', class: 'free-logo'
          .saling__else2
            出品中の商品がありません
  .sale__item--bottom
    = render "/shared/footer"

app/views/users/selling.html.haml
.selling__item.crearfix
  .selling__item--top
    = render "/shared/header-login"
  .selling__item__sidebar
    = render "/shared/sidebar"
  .selling__item--redcircle
    = render "/shared/sell-icon"
    .selling__item__box
      .selling__item__box__main
        出品した商品
      .selling__item__box__selling
        = link_to "出品中", selling_items_user_path, class: "note"
      .selling__item__box__sale
        = link_to "取引中", selling_user_path, class: "note"
      .selling__item__box__sold
        = link_to "売却済み", sold_user_path, class: "note"
      .selling__item__box__list
        .selling
        - if @items.present?
          - @items.each do |item|
            .selling__all
              = item.name
        - else
          .selling__else
            = image_tag "logo_white.svg", height: '120px', width: '120px', class: 'free-logo'
          .selling__else2
            取引中の商品がありません
  .selling__item--bottom
    = render "/shared/footer"

app/views/users/selling_items.html.haml
.users__show
  .users__show__top
    = render "shared/header-login"
    .indenti-crumbs
      - breadcrumb :mypage
      = render "layouts/breadcrumbs"

  .sell-icon
    = render "/shared/sell-icon"

  .content.clearfix
    = render "shared/sidebar"
    .right
      .bought
        .bought__items
          出品した商品
        .bought__status
          %ul.trader
            %li.trader__change.movie
              出品中
            %li.trader__change
              過去の取引
        .bought__text
          %ul.bought__text__list
            %li.bought__text__list--message.see
              取引中の商品がありません
            %li.bought__text__list--message
              - @items.each do |item|
                = link_to item.name, item_path(item)
                
  .users__show__bottom
    = render "shared/footer"

app/views/users/show.html.haml
.users__show
  .users__show__top
    = render "shared/header-login"
    .indenti-crumbs
      - breadcrumb :mypage
      = render "layouts/breadcrumbs"

  .sell-icon
    = render "/shared/sell-icon"

  .content.clearfix
    = render "shared/sidebar"
    .right
      = link_to zoom_user_path(current_user.id) do
        .right__up
          .right__up__profil
            .right__up__profil--user
            .right__up__profil--name
              = current_user.nickname
            .right__up__profil__box
              .right__up__profil__box--goods
                評価
              .right__up__profil__box--items
                出品数
              .right__up__profil__box--items-number
                = current_user.items.length
      .right__middle
        %ul.tab
          %li.tab__info.active
            お知らせ
          %li.tab__info
            やることリスト
      .right__down
        %ul.right__down__main.show
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    切り替え後
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    切り替え後
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    切り替え後
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    切り替え後
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    切り替え後
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__list
            .right__down__main__list__box
              .right__down__main__list__box__inbox
                = link_to "" do
                  一覧を見る
        %ul.right__down__main
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    ニュース
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    ニュース
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    ニュース
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    ニュース
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__box
            = link_to "" do
              .right__down__main__box__inbox
                .right__down__main__box__inbox__logo
                  = image_tag "logo_red.svg"
                .right__down__main__box__inbox__inner
                  .right__down__main__box__inbox__inner--text
                    ニュース
                  .right__down__main__box__inbox__inner--time
                    時間
                .right__down__main__box__inbox--arrow
                  = fa_icon "chevron-right", class: "right__arrow"
          %li.right__down__main__list
            .right__down__main__list__box
              .right__down__main__list__box__inbox
                = link_to "" do
                  一覧を見る
      .bought
        .bought__items
          購入した商品
        .bought__status
          %ul.trader
            %li.trader__change.movie
              取引中
            %li.trader__change
              過去の取引
        .bought__text
          %ul.bought__text__list
            %li.bought__text__list--message.see
              取引中の商品がありません
            %li.bought__text__list--message
              過去の取引がありません
                


  .users__show__bottom
    = render "shared/footer"

app/views/users/sign_up.html.haml
.contents
  .header
    .fmarket
      .fmarket__box
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg",class: "logo"
    .clearfix
      .progress-bar1
        .a
          会員情報
        .progress-bar1__x
      .progress-bar2
        電話番号認証
        .progress-bar2__x
      .progress-bar3
        お届け先住所入力
        .progress-bar3__x
      .progress-bar4
        支払い方法
        .progress-bar4__x
      .progress-bar5
        .bbb
          完了
        .progress-bar5__x
  .single
  = form_with model: @user, url: sms_confirmation_signup_index_path, class: :single, local: true do |f|
    .single__head
      %h1
        会員情報入力
    .single-box
      = @user.errors.full_messages
      .single-box2
        %li
          ニックネーム
        .single-box3
          必須
        
        - if @user.errors.messages[:nickname].any?
          .field-input
            = f.text_field :nickname, autofocus: true, class: 'user_nickname_error', id: 'nickname', placeholder: '例）フリマ123'
            = render 'shard/signups_errors', errors: @user.errors.full_messages_for(:nickname)
        - else
          .field-input
            = f.text_field :nickname, autofocus: true, class: 'user_nickname', id: 'nickname', placeholder: '例）フリマ123'
      .single-box4
        %li
          メールアドレス
        .single-box5
          必須
        
        - if @user.errors.messages[:nickname].any?
          .field-input
            = f.text_field :email, autofocus: true, class: 'user_nickname_error', id: 'email'
            = render 'shard/signups_errors', errors: @user.errors.full_messages_for(:email)
        - else
          .field-input
            = f.text_field :email, autofocus: true, class: 'user_email', id: 'email'
 
      .single-box8
        %h2
          本人確認
        .option
          %p
            安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
      .single-box9
        %li
          お名前(全角)
        .single-box10
          必須
        = f.text_field :family_name, placeholder: "例) 山田", type: "text", class: "input-default"
        = f.text_field :last_name, placeholder: "例) 彩", type: "text",class: "input-default"
      .single-box9
        %li
          お名前カナ(全角)
        .single-box11
          必須
        = f.text_field :j_family_name, placeholder: "例) ヤマダ", type: "text",class: "input-default"
        = f.text_field :j_last_name, placeholder: "例) アヤ", type: "text",class: "input-default"
      .single-box13
        %li
          生年月日
        .single-box14
          必須
        .icons
          = fa_icon "chevron-down"
          %i= fa_icon "chevron-down"
          %i= fa_icon "chevron-down"
        = f.collection_select :birthday_year_id, BirthdayYear.all, :id, :name
        = f.collection_select :birthday_month_id, BirthdayMonth.all, :id, :name
        = f.collection_select :birthday_day_id, BirthdayDay.all, :id, :name
        .caution
          %p
            ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
      .the_box
        %iframe{frameborder: "0", name: "a-x6czxoic852l", role: "presentation", sandbox: "allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox", scrolling: "no", src: "https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfZGCYTAAAAAHoK-s7Lg5OdYg5Fq4susvALmZoc&co=aHR0cHM6Ly93d3cubWVyY2FyaS5jb206NDQz&hl=ja&v=75nbHAdFrusJCwoMVGTXoHoM&size=normal&cb=8by6abyui13", }
        #g-recaptcha-response.g-recaptcha-response{name: "g-recaptcha-response",}
      .caution2
        「次へ進む」のボタンを押すことにより、
        %a{href: "/jp/tos_list/", target: "_blank"}> 利用規約
        に同意したものとみなします
      .button_box
        = f.submit "次へ進む", class: "btn-default btn-red"
      .last_text
        %p
          %a{href: "/jp/help_center/article/423/", target: "_blank"}> 本人情報の登録について
          = fa_icon "chevron-right"
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "フリマ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari

app/views/users/sold.html.haml
.sold__item.crearfix
  .sold__item--top
    = render "/shared/header-login"
  .sold__item__sidebar
    = render "/shared/sidebar"
  .sold__item--redcircle
    = render "/shared/sell-icon"
    .sold__item__box
      .sold__item__box__main
        出品した商品
      .sold__item__box__sale
        = link_to "出品中", selling_items_user_path, class: "note"
      .sold__item__box__sell
        = link_to "取引中", selling_user_path, class: "note"
      .sold__item__box__sold
        = link_to "売却済み", sold_user_path, class: "note"
      .sold__item__box__list
        .soldx
          - if @items.present?
            - @items.each do |item|
              .soldx__all
                = item.name
          - else
            .soldx__else
              = image_tag "logo_white.svg", height: '120px', width: '120px', class: 'free-logo'
            .soldx__else2
              売却済みの商品がありません
  .sold__item--bottom
    = render "/shared/footer"