config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :new,
  controllers: {
    # sessions: 'users/sessions',
    # registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
    get 'new' => 'devise/sessions#new'
    post 'create' => 'devise/sessions#create'
  end

  root to: "items#index"

  resources :sign_ups, only: [:index] do
    collection do
      get :registration  # 登録情報の一部を入力してもらう
      post :registration, to: 'signups#step1_validates'  #step1で入力したデータのバリデーションチャックをする(詳しくはコントローラーで説明) render後にリロードしてもエラーが出ないようにget'step1'とURLは同じに設定する
      get :sms_confirmation  # 残りの登録情報を入力してもらう
      post :sms_confirmation, to: 'signups#create' # 入力した情報すべてを保存 こっちもrenderするなら揃える
    end
  end

  resources :items do
    collection do
      get :buy
      get :buy1
    end
    member do
      get :details
      get :address
      get :buy
      get :confimation
      post :confimation
      post :buy1
    end
  end    
  resources :pays, only: [:new]
  resources :users, only: [:new, :create, :show, :edit, :destroy] do
    collection do
      get :login
    end
    member do
      get :identification
      get :logout
      get :profile
      post :profile
      get :selling
      get :saling
      get :sold
      get :selling_items
      get :card_info
      get :zoom
    end
  end
  resources :signup, only: [:create] do
    collection do
      get :registration
      get :sms_confirmation
      post :sms_confirmation
      get :address
      post :address
      get :card
      post :card
      get :complete
      post :complete
      get :logout
    end
    member do
      get :identification
      get :saling
      get :selling
      get :sold
    end
  end

  resources :cards, only: [:index, :create, :new] do
    member do 
      get :buy
      get :confimation
      post :confimation
      get :completed
      # post 'confimation/:id'=> 'cards#confimation', as: 'confimation' #httpメソッドはpostなので注意
      # get  'completed'=>  'cards#completed', as: 'completed'
    end
  end
end

app/views/shared/_contents-item.html.haml
.contents__category__main__item
  - @items.each do |item|
    .contents__category__main__item__box
      .contents__category__main__item__box__in
        .contents__category__main__item__box__in__image
          = link_to details_item_path(item) do
            = image_tag "#{item.thumbnails.last.images}"
        .contents__category__main__item__box__in__price
          .contents__category__main__item__box__in__price__tag
            = item.price.to_s(:delimited)
        .contents__category__main__item__box__in__text
          .contents__category__main__item__box__in__text__write
            = item.name
      .contents__category__main__item__box__in__text

app/views/shared/_footer.html.haml
.footer-top
  .footer-top__center
    .footer-top__center-left
      .footer-top__center-left__text
        .footer-top__center-left__text-upper
          スマホでかんたんフリマアプリ
        .footer-top__center-left__text-bottom
          今すぐ無料ダウンロード！
        .footer-top__center-left__icon
          = image_tag "logo_red.svg", height: '60px', width: '60px', class: 'free-logo'
          = image_tag "https://developer.apple.com/app-store/marketing/guidelines/images/badge-download-on-the-app-store.svg", class: "apple-bar"
          = image_tag "https://play.google.com/intl/ja/badges/static/images/badges/en_badge_web_generic.png", class: "google-bar"
    .footer-top__center-right
      = image_tag "phone.jpeg", class: "sp"
.footer-bottom
  .footer-bottom__center
    .footer-bottom__center-about
      .footer-bottom__center-about-title
        メルカリについて
      .footer-bottom__center-about-contents
        .about-company
          = link_to "会社概要 (運営会社)", "https://about.mercari.com/"
        .recrute
          = link_to "採用情報", "https://careers.mercari.com/"
        .prerilease
          = link_to "プレスリリース", "https://about.mercari.com/press/news/"
        .blog
          = link_to "公式ブログ", "https://jp-news.mercari.com/"
        .logo-guidline
          = link_to "メルカリロゴ利用ガイドライン", "https://www.mercari.com/jp/logo-guidelines/"
        .sns-twitter
          = link_to "", class: "t-url" do
            = image_tag "Twitter_Logo_WhiteOnImage.png", class: "twitter"
        .sns-facebook
          = link_to "https://www.facebook.com/mercarijp", class: "f-url" do
            = image_tag "f_logo_RGB-White_1024.png", class: "facebook"
    .footer-bottom__center-help
      .footer-bottom__center-help-title
        ヘルプ＆ガイド
      .footer-bottom__center-help-contents
        .mercari-guide
          = link_to "メルカリガイド", "https://www.mercari.com/jp/help_center/"
        .raku-ship
          = link_to "らくらくメルカリ便", "https://www.mercari.com/jp/rakuraku-mercari/"
        .yuu-ship
          = link_to "ゆうゆうメルカリ便", "https://www.mercari.com/jp/yuyu-mercari/"
        .bigger-ship
          = link_to "大型メルカリ便", "https://www.mercari.com/jp/rakuraku-ogata/"
        .car-guide
          = link_to "車体取引ガイド", "https://www.mercari.com/jp/guide/car/"
        .safe-secure
          = link_to "メルカリあんしん・あんぜん宣言！", "https://www.mercari.com/jp/safe/description/"
        .fake-eradication
          = link_to "偽ブランド品撲滅への取り組み", "https://www.mercari.com/jp/authenticity/"
        .mercari-box
          = link_to "メルカリボックス", "https://www.mercari.com/jp/box/"
    .footer-bottom__center-privacy
      .footer-bottom__center-privacy-title
        プライバシーと利用規約
      .footer-bottom__center-privacy-contents
        .footer-bottom__center-privacy-contents__left
          .privacy-policy
            = link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
          .mercari-terms
            = link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
          .suport-terms
            = link_to "あんしんスマホサポート制度に関する利用規約", "https://www.mercari.com/jp/tos_smartphone_support/"
          .compliance
            = link_to "コンプライアンスポリシー", "https://www.mercari.com/jp/compliance/"
        .footer-bottom__center-privacy-contents__right
          .personal-management
            = link_to "個人データの安全管理に係る基本方針", "https://www.mercari.com/jp/data_security/"
          .specific-notation
            = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
          .settlement
            = link_to "資金決算報告に基づく表示", "https://www.mercari.com/jp/shikin_kessai/"
          .legal
            = link_to "法令順守と犯罪抑止のために", "https://about.mercari.com/sustainability/safe-secure-and-fair-transactions/"
    .footer-bottom__center-country
      .footer-bottom__center-country-title
        国
      .footer-bottom__center-country-contents
        .japan
          = link_to "日本", "https://www.mercari.com/jp/"
        .united-states
          = link_to "United States", "https://www.mercari.com/"
    .footer-bottom__center-logo
    
.under
  .under-logo
    = link_to "root_path" do
      = image_tag "fmarket_logo_white_white.svg", class: "f_logo"
  .under-since
    © 2019 freemarket

app/views/shared/_header-login.html.haml
.header
  .main
    .main__top
      .main__top__left
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg", class: "merukari-logo"
      .main__top__right
        %input.search-form__input{name: "keyword", placeholder: "何かお探しですか？", type: "text", value: ""}
        %i.icon-search
          = fa_icon  "search", class: 'icon' 
    .main__bottom
      .main__bottom__left
        .main__bottom__left__category
          .logo1
            = fa_icon  "list-ul",class: 'icon1'
          .category-word
            %ul 
              %li カテゴリーから探す
        .main__bottom__left__brand
          .logo1
            = fa_icon  "tags lg",class: 'icon1'
          .category-word
            %ul 
              %li ブランドから探す
      - if user_signed_in? 
        .main__bottom__right  
          .main__bottom__right__nice
            .logo-heart
     
            .nice-word
              %ul
                %li いいね！一覧
          .main__bottom__right__information
            .logo-bell
            .information-word
              %ul
                %li お知らせ
          .main__bottom__right__list
            .logo2
              = fa_icon  "check lg",class: "icon2"
            .list-word
              %ul
                %li やることリスト
          .main__bottom__right__my-page
            .logo2
              = image_tag "https://static.mercdn.net/images/member_photo_noimage_thumb.png", class: 'logo-my'
            = link_to user_path(current_user.id) do
              .my-page-word
                %ul
                  %li マイページ
      - else 
        .main__bottom__right  
          .logout
            .logout__new
              = link_to new_user_path do
                .logout__new__text
                  新規登録
            .logout__rogin
              = link_to new_user_session_path do
                .logout__rogin__text
                  ログイン

app/views/shared/_sell-icon.html.haml
- if user_signed_in?
  .sell-icon
    = link_to new_item_path do
      .red-circle
        %p.text 出品
        = fa_icon 'camera', class: "camera"
- else

app/views/shared/_sidebar.html.haml
.left
  .left__top
    %ul
      %li
        = link_to "マイページ", class: "note"
      %li
        = link_to "お知らせ"
      %li
        = link_to "やることリスト", class: "note"
      %li
        = link_to "いいね！一覧", class: "note"
      %li
        = link_to "出品する", new_item_path, class: "note"
      %li
        = link_to "出品した商品・出品中", selling_items_user_path, class: "note"
      %li
        = link_to "出品した商品・取引中", selling_user_path, class: "note"
      %li
        = link_to "出品した商品・売却済み", sold_user_path, class: "note"
      %li
        = link_to "購入した商品・取引中", class: "note"
      %li
        = link_to "購入した商品・過去の取引", class: "note"
      %li
        = link_to "ニュース一覧", class: "note"
      %li
        = link_to "評価一覧", class: "note"
      %li
        = link_to "ガイド", class: "note"
      %li
        = link_to "お問い合わせ", class: "note"
  .left__center
    メルペイ
    .left__center__box
      %li
        = link_to "売上・振込申請", class: "note"
      %li
        = link_to "ポイント", class: "note"
  .left__bottom
    設定
    .left__bottom__box
      %li
        = link_to "プロフィール",profile_user_path, class: "note"
      %li
        = link_to "発送元・お届け先住所変更", class: "note"
      %li
        = link_to "支払い方法",new_card_path, class: "note"
      %li
        = link_to "メール/パスワード", class: "note"
      %li
        = link_to "本人情報",identification_user_path, class: "note"
      %li
        = link_to "電話番号の確認", class: "note"
      %li
        = link_to "ログアウト", logout_user_path,method: :get ,class: "note"