config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :new,
  controllers: {
    # sessions: 'users/sessions',
    # registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
    get 'new' => 'devise/sessions#new'
    post 'create' => 'devise/sessions#create'
  end

  root to: "items#index"

  resources :sign_ups, only: [:index] do
    collection do
      get :registration  # 登録情報の一部を入力してもらう
      post :registration, to: 'signups#step1_validates'  #step1で入力したデータのバリデーションチャックをする(詳しくはコントローラーで説明) render後にリロードしてもエラーが出ないようにget'step1'とURLは同じに設定する
      get :sms_confirmation  # 残りの登録情報を入力してもらう
      post :sms_confirmation, to: 'signups#create' # 入力した情報すべてを保存 こっちもrenderするなら揃える
    end
  end

  resources :items do
    collection do
      get :buy
      get :buy1
    end
    member do
      get :details
      get :address
      get :buy
      get :confimation
      post :confimation
      post :buy1
    end
  end    
  resources :pays, only: [:new]
  resources :users, only: [:new, :create, :show, :edit, :destroy] do
    collection do
      get :login
    end
    member do
      get :identification
      get :logout
      get :profile
      post :profile
      get :selling
      get :saling
      get :sold
      get :selling_items
      get :card_info
      get :zoom
    end
  end
  resources :signup, only: [:create] do
    collection do
      get :registration
      get :sms_confirmation
      post :sms_confirmation
      get :address
      post :address
      get :card
      post :card
      get :complete
      post :complete
      get :logout
    end
    member do
      get :identification
      get :saling
      get :selling
      get :sold
    end
  end

  resources :cards, only: [:index, :create, :new] do
    member do 
      get :buy
      get :confimation
      post :confimation
      get :completed
      # post 'confimation/:id'=> 'cards#confimation', as: 'confimation' #httpメソッドはpostなので注意
      # get  'completed'=>  'cards#completed', as: 'completed'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery
  belongs_to_active_hash :estimated_shipping_date
  belongs_to_active_hash :state
  belongs_to_active_hash :shipping_method
  belongs_to :user, optional: true
  has_many :comments
  has_many :goods
  validates :name, :price, :text, :prefecture_id, :delivery_id, :state_id, :estimated_shipping_date_id, presence: true
  validates :prefecture_id,:delivery_id,:delivery_id,:state_id,numericality:{greater_than_or_equal_to:1}

  #belongs_to :category
  belongs_to :saler, optional: true, class_name: "User"
  belongs_to :buyer, optional: true, class_name: "User"
  has_many :thumbnails, dependent: :destroy
  accepts_nested_attributes_for :thumbnails, allow_destroy: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:details, :show, :edit, :update, :destroy, :buy, :confimation]
  before_action :set_details, only: [:details, :show, :buy]
  before_action :set_card, only: [:confimation]
  
  def index
    @items = Item.all.limit(10).order(id: "DESC")
  end
  
  def new
    @item = Item.new
    @item.thumbnails.build
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
     
      if @item.save
          params[:thumbnails][:images].each do |image|
            @item.thumbnails.create(images: image, item_id: @item.id)
          end
        format.html{redirect_to root_path}
      else
        @item.thumbnails.build
        format.html{render action: 'new'}
      end
    end
  end

  def edit
  end

  def update
    item = Item.first
    # item.thumbnails.images = MiniMagick::Image.read(open(URI.encode(item.thumbnails.images), &:read))
    # item.save!
    if @item.update!(item_params) 
      redirect_to root_path
    else
      redirect_to edit_item_path
    end
  end

  def details
    
  end
  
  def address
  end

  def buy
    if @item.saler.id == current_user.id
       redirect_to root_path
    else
      @price = "¥#{@item.price.to_s(:delimited)}"
    end
  end

  def confimation
    if @card.blank?
      redirect_to controller: "cards", action: "new"
      flash[:alert] = '購入にはクレジットカード登録が必要です'
    else
    
     # 購入した際の情報を元に引っ張ってくる
     card = current_user.card
      
      #.find(params[id])後にしようします。
     # テーブル紐付けてるのでログインユーザーのクレジットカードを引っ張ってくる
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
     # キーをセットする(環境変数においても良い)
      Payjp::Charge.create(
      amount: @item.price, #支払金額
      customer: card.customer_id, #顧客ID
      currency: 'jpy', #日本円
      )
     # ↑商品の金額をamountへ、cardの顧客idをcustomerへ、currencyをjpyへ入れる
      if @item.update(buyer_id: current_user.id)
        
        flash[:notice] = '購入しました。'
        # render template: "cards/completed" 
        redirect_to controller: "cards", action: 'completed'
      else
        flash[:alert] = '購入に失敗しました。'
        # redirect_to controller: "items", action: 'show'
      end
     #↑この辺はこちら側のテーブル設計どうりに色々しています
    end
  end

  def buy1
  end

  def show
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

private


  def item_params
    params.require(:item).permit(:name, :size, :state_id, :delivery_id, :estimated_shipping_date_id, :price, :text, :prefecture_id,  thumbnails_attributes: [:images, :id, :_destroy]).merge(user_id: current_user.id, saler_id: current_user.id)
  end
  
  def set_item
    @item = Item.find(params[:id])
  end
  
  def set_details
    @items = Item.where(saler_id: @item.saler_id).limit(6).order('id DESC')
    @price = "¥#{@item.price.to_s(:delimited)}"
    @state = @item.state.name
    @delivery = @item.delivery.name
    @date = @item.estimated_shipping_date.name
  end

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/buy.html.haml
.contents
  .header
    .header__box
      = link_to root_path do
        = image_tag "fmarket_logo_red.svg"
.buy
  .buy__main
    %p.details 購入内容の確認
    .buy__main__pay
      .buy__main__pay__inner
        -# .buy__main__pay__inner__image
        -#   = image_tag "https://cdn.pixabay.com/photo/2019/11/09/14/28/camera-4613669__480.jpg", class: "image-item"
        -#   %p.image-textエスニック柄ワイルドパンツ
        -# .buy__main__pay__inner__pay
        -#   %p.buy-price-1
        -#     ¥980
        -#     %span.item-shipping-fee 送料込み

        .buy__main__pay__inner__point
          %p.buy-point ポイントはありません
        .buy__main__pay__inner__price
          %li.buy-text  支払い金額
          %li.buy-price-2 
            = @price
        .buy__main__pay__inner__button
            
          = form_tag(action: :confimation, method: :post) do
            :plain
            %script.payjp-button{:src => "https://checkout.pay.jp", :type => "text/javascript" ,"data-text" => "購入する" ,"data-key" => "pk_test_36c760ac84cc0be08c976196"}


    -# .buy__main__address
    -#   .buy__main__address__inner
    -#     .buy__main__address__inner__area
    -#       %p 配送先 
    -#     .buy__main__address__inner__info
    -#       %p 〒547-****
    -#       %p 大阪府大阪府大阪市****
    -#       %p メルカリ 太郎
    -#     .buy__main__address__inner__fix
    -#       %a.buy-user-info-fix{href: "#"}
    -#         %span 変更する
    -#         %i.icon-check
    -#         = fa_icon  "chevron-right", class: 'buy-icon' 

    -# .buy__main__card
    -#   .buy__main__card__inner
    -#     .buy__main__card__inner__way
    -#       %p 支払方法
    -#     .buy__main__card__inner__text
    -#       %p ***************1111
    -#       %p 01/25 
    -#     .buy__main__card__innner__type
    -#       = image_tag "https://cdn.pixabay.com/photo/2017/08/10/14/02/visa-2623015_1280.png", class: "image-visa"
          
        
    -#     .buy__main__card__inner__fix  
    -#       %a.buy-user-info-fix{href: "#"}
    -#         %span 変更する
    -#         %i.icon-check
            = fa_icon  "chevron-right", class: 'buy-icon'        
.main-footer
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari

app/views/items/buy1.html.haml
.contents
  .header
    .header__box
      = link_to root_path do
        = image_tag "fmarket_logo_red.svg"
        
.sold
  .sold__content
    .sold__content__top
      %h2.soldtop-text 商品は既に売り切れています
    .sold__content__bottom
      .sold__content__bottom__text
        %a.sold-back{href: "#"}
          %span 商品画面へ戻る
  
.main-footer
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3
      © 2019 Mercari

app/views/items/details.html.haml
.topper
  = render "shared/header-login" 

.details
  .contents
    .contents__box
      .contents__item__name
        = @item.name

      .contents__item__main
        .item-phot
          .item-phot-upper
          .item-phot-low
            .item-phot-low-in
              .thumbnail
                = image_tag "#{@item.thumbnails.last.images}"

        .item-detail-table
          .item-detail-table-box
            .item-detail-table-Exhibitor
              .name
                .name-bar
                  出品者
              .text
                .user-name
                  = @item.user.nickname
                .markbox
                  .markbox-good
                    .mark-1
                      = fa_icon 'smile'
                    .num
                      3
                  .markbox-usually
                    .mark-2
                      = fa_icon 'meh'
                    .num
                      2
                  .markbox-bad
                    .mark-3
                      = fa_icon 'frown'
                    .num
                      1

            .item-detail-table-category
              .name
                .name-bar
                  カテゴリー
              .text
                .text__1
                  メンズ
                .text__2
                  .icon
                    >
                  .bar
                    靴
                .text__3
                  .icon
                    >
                  .bar
                    スニーカー
            .item-detail-table-brand
              .name
                .name-bar
                  ブランド
              .text
                .text__1
                  ニューバランス
            .item-detail-table-size
              .name
                .name-bar
                  サイズ
              .text
                .text__1
                  26.5cm
            .item-detail-table-status
              .name
                .name-bar
                  商品の状態
              .text
                .text__1
                  = @state
            .item-detail-table-charge
              .name
                .name-bar
                  配送料の負担
              .text
                .text__1
                  = @delivery
            .item-detail-table-method
              .name
                .name-bar
                  配送の方法
              .text
                .text__1
                  ゆうパック
            .item-detail-table-region
              .name
                .name-bar
                  配送元地域
              .text
                .text__1
                  = @item.user.address.prefecture.name
            .item-detail-table-indication
              .name
                .name-bar
                  発送日の目安
              .text
                .text__1
                  = @date
                  
        .item-pricebox
          .item-price
            = @price
          .item-tax
            (税込) 
          .item-fee
            送料込み
        %ul.item-btn
          %li.item-btn-in
            = link_to "購入画面に進む", buy_item_path(@item)
          

        .item-description
          .item-description__in
            %p
              = @item.text
            
        .item-btn-box
          .item-btn-box-left
            .item-btn-box-like
              .item-btn-box-like-in
                .icon
                  = fa_icon 'heart-o lg'
                .like
                  いいね!
                .num
                  10
            .item-btn-box-report
              .item-btn-box-report-in
                .icon
                  = fa_icon 'flag'
                %ul.inappropriate
                  %li.inappropriate-in
                    = link_to "不適切な商品の報告", "https://www.yahoo.co.jp/"
          .item-btn-box-right
            .item-btn-box-right-in
              .icon
                = fa_icon 'lock'
              %ul.support
                %li.support-in
                  = link_to "あんしん・あんぜんへの取り組み", "https://www.yahoo.co.jp/", class:"support-in-a"

    .itemlink
      .itemlink-bar
        %ul.itemlink-bar__left
          .itemlink-bar__left-icon
            <
          %li.itemlink-bar__left
            = link_to "前の商品", "https://www.yahoo.co.jp/", class:"itemlink-bar__left-a"
            
        .itemlink-bar__right
          %ul.itemlink-bar__right
            %li.itemlink-bar__right
              = link_to "次の商品", "https://www.yahoo.co.jp/", class:"itemlink-bar__right-a"
            .itemlink-bar__right-icon
              >
    .media-box
      .media-box-in
        .logo-box
          .fb-icon
            -# = fa_icon 'facebook' fa-icon使用する時用に置いておきます。
          .tw-icon
            -# = fa_icon 'twitter'
          .pt-icon
            -# = fa_icon 'pinterest'
    .another-item
      .another-item-in
        = "#{@item.user.nickname}さんのその他の出品"
    .another-image.clearfix
      .another-image-box
        .another-image-box-in
          - @items.each do |item|
            .image-box
              .image-box-in
                = image_tag "#{item.thumbnails.last.images}", width: "220", height: "220"
              .text-box
                .text-box-in
                  = item.name
                .item-box-num
                  .price-box
                    = "¥#{item.price.to_s(:delimited)}"
                    .price-in
                  .num-box
                    .nice
                      = fa_icon 'heart'
                    .num
                      10
    .another-brand
      .another-brand-in
        ニューバランスのスニーカー その他の商品
    .another-brand-image
      .another-brand-image-box
        .another-image-box-in
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
        .another-image-box-in
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
.bread-crumbs
  .bread-crumbs-in
    .left-bar
      .home
        メルカリ
      .icon
        >
    .right-bar
      .item
        ニューバランス New Balance 1400 26.5cm ホワイト
.footer
  = render "shared/footer"

app/views/items/edit.html.haml
.contents
  .header
    .header__box
      = link_to root_path do
        = image_tag "fmarket_logo_red.svg"

.sell-main
  .sell
  = form_with model: @item, url: item_path, class: :indenti_forms ,local: true do |f|
    .sell__inner  
      .sell__inner__top
        %h2.sell-info 商品の情報を入力
      .sell__inner__upload
        .sell__inner__upload__img-text
          %h2.sent-left 出品画像
          %h2.sell-right 必須
        .sell__inner__upload__img-text2
          %h2.img-text-up 最大10枚までアップロードできます
        = f.fields_for :thumbnails do |image|
          .sell__inner__upload__img-file
            = image_tag "#{@item.thumbnails.last.images}"
            .sell__inner__upload__img-file__container
              %label
                = image.file_field :images, class: 'hidden', style: "display: none;"
                .file-box
                  %pre.file-up
                    :preserve
                      ドラッグアンドドロップ
                      またはクリックしてファイルをアップロード

      .sell__inner__content
        .sell__inner__content__item
          %h2.sent-left 商品名
          %h2.sell-right 必須
        .sell__inner__content__name
          = f.text_field :name, placeholder: "商品名（必須 40文字まで)",class: :input_default
        .sell__inner__content__description
          %h2.sent-left 商品の説明
          %h2.sell-right 必須
        .sell__inner__content__deteil
          = f.text_area :text,placeholder:"商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5" ,class: :textarea_default 
      .sell__inner__category  
        %h2.text-inline  商品詳細
        .category-box
          .sell__inner__category__name
            %h2.sent-left カテゴリー
            %h2.sell-right 必須
          .sell__inner__category__box1
            .select-sell
              %i.icon-arrow-sell
                = fa_icon "chevron-down"
              .select-sell
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name 
          .sell__inner__category__status
            %h2.sent-left 商品の状態
            %h2.sell-right 必須
          .sell__inner__category__box2
            .select-sell
              %i.icon-arrow-sell 
                = fa_icon "chevron-down"
              .select-sell
                = f.collection_select :state_id, State.all, :id, :name 
      .sell__inner__delivery 
        %h2.text-inline 発送について
        = link_to "?", "", class: "qestion-mark" 
        .delivery-box  
          .sell__inner__delivery__fee
            %h2.sent-left 配送料の負担
            %h2.sell-right 必須
          .select-sell
            %i.icon-arrow-sell
              = fa_icon "chevron-down"
            .select-sell
              = f.collection_select :delivery_id, Delivery.all, :id, :name 
          .sell__inner__delivery__region
            %h2 発送元の地域
            %h2.sell-right  必須
          .select-sell
            %i.icon-arrow-sell
              = fa_icon "chevron-down"
            .select-sell
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name 
          .sell__inner__delivery__day
            %h2.sent-left 発送までの日数
            %h2.sell-right 必須
          .select-sell
            %i.icon-arrow-sell
              = fa_icon "chevron-down"
            .select-sell
              = f.collection_select :estimated_shipping_date_id, EstimatedShippingDate.all, :id, :name  

      .sell__inner__price
        %h2.text-inline 販売価格(300〜9,999,999)
        = link_to "?", "", class: "qestion-mark" 
        .sell__inner__price__box
          %ul
            %li.sell-price-form
              .price-box-top
                %h2.sent-left 価格
                %h2.sell-right 必須
              .sell-price-input  
                %h2.price-box-top ¥
                = f.text_field :price, class: :input_sell
            %li.sell-price-center
              .l-left
                販売手数料 (10%)
              .l-right -
            %li.sell-price-bold
              .l-left 販売利益
              .l-right ¥450

      .sell__inner__privacy
        .sell__inner__privacy__top
          %div.privacy1
            %p
              = link_to "禁止されている出品", ""
              = link_to "行為",""
              を必ずご確認ください。
          %div.privacy2
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "偽ブランドの販売", ""
              は犯罪であり処罰される可能性があります。
          %div.privacy3
            %p
              また、出品をもちまして
              = link_to "加盟店規約",""
              に同意したことになります。
        .sell__inner__privacy__exhibit
          = f.submit '編集する', class: :exhibit_btn
          = link_to "もどる", class: "sell-back"

.main-footer
  .footer
    %ul.footer__box
      %li= link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li= link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
      %li= link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    .footer__box2
      = link_to root_path do
        = image_tag "fmarket_logo_white.svg" , height: "60", width: "150"
    .footer__box3

      © 2019 Mercari

app/views/items/show.html.haml
.topper
  = render "shared/header-login" 

.details
  .contents
    .contents__box
      .contents__item__name
        = @item.name

      .contents__item__main
        .item-phot
          .item-phot-upper
          .item-phot-low
            .item-phot-low-in
              .thumbnail
                = image_tag "#{@item.thumbnails.last.images}"

        .item-detail-table
          .item-detail-table-box
            .item-detail-table-Exhibitor
              .name
                .name-bar
                  出品者
              .text
                .user-name
                  = @item.user.nickname
                .markbox
                  .markbox-good
                    .mark-1
                      = fa_icon 'smile'
                    .num
                      3
                  .markbox-usually
                    .mark-2
                      = fa_icon 'meh'
                    .num
                      2
                  .markbox-bad
                    .mark-3
                      = fa_icon 'frown'
                    .num
                      1

            .item-detail-table-category
              .name
                .name-bar
                  カテゴリー
              .text
                .text__1
                  メンズ
                .text__2
                  .icon
                    >
                  .bar
                    靴
                .text__3
                  .icon
                    >
                  .bar
                    スニーカー
            .item-detail-table-brand
              .name
                .name-bar
                  ブランド
              .text
                .text__1
                  ニューバランス
            .item-detail-table-size
              .name
                .name-bar
                  サイズ
              .text
                .text__1
                  26.5cm
            .item-detail-table-status
              .name
                .name-bar
                  商品の状態
              .text
                .text__1
                  = @state
            .item-detail-table-charge
              .name
                .name-bar
                  配送料の負担
              .text
                .text__1
                  = @delivery
            .item-detail-table-method
              .name
                .name-bar
                  配送の方法
              .text
                .text__1
                  ゆうパック
            .item-detail-table-region
              .name
                .name-bar
                  配送元地域
              .text
                .text__1
                  = @item.user.address.prefecture.name
            .item-detail-table-indication
              .name
                .name-bar
                  発送日の目安
              .text
                .text__1
                  = @date
                  
        .item-pricebox
          .item-price
            = @price
          .item-tax
            (税込) 
          .item-fee
            送料込み
        %ul.item-btn
          %li.item-btn-in
            = link_to "編集する",  edit_item_path(@item)
        %ul.item-btn1
          %li.item-btn-in
            = link_to "削除", item_path(@item), method: :delete
        
          

        .item-description
          .item-description__in
            .p
              = @item.text
            
        .item-btn-box
          .item-btn-box-left
            .item-btn-box-like
              .item-btn-box-like-in
                .icon
                  = fa_icon 'heart-o lg'
                .like
                  いいね!
                .num
                  10
            .item-btn-box-report
              .item-btn-box-report-in
                .icon
                  = fa_icon 'flag'
                %ul.inappropriate
                  %li.inappropriate-in
                    = link_to "不適切な商品の報告", "https://www.yahoo.co.jp/"
          .item-btn-box-right
            .item-btn-box-right-in
              .icon
                = fa_icon 'lock'
              %ul.support
                %li.support-in
                  = link_to "あんしん・あんぜんへの取り組み", "https://www.yahoo.co.jp/", class:"support-in-a"

    .itemlink
      .itemlink-bar
        %ul.itemlink-bar__left
          .itemlink-bar__left-icon
            <
          %li.itemlink-bar__left
            = link_to "前の商品", "https://www.yahoo.co.jp/", class:"itemlink-bar__left-a"
            
        .itemlink-bar__right
          %ul.itemlink-bar__right
            %li.itemlink-bar__right
              = link_to "次の商品", "https://www.yahoo.co.jp/", class:"itemlink-bar__right-a"
            .itemlink-bar__right-icon
              >
    .media-box
      .media-box-in
        .logo-box
          .fb-icon
            -# = fa_icon 'facebook' fa-icon使用する時用に置いておきます。
          .tw-icon
            -# = fa_icon 'twitter'
          .pt-icon
            -# = fa_icon 'pinterest'
    .another-item
      .another-item-in
        = "#{@item.user.nickname}さんのその他の出品"
    .another-image
      .another-image-box
        .another-image-box-in
          - @items.each do |item|
            .image-box
              .image-box-in
                = image_tag "#{item.thumbnails.last.images}", width: "220", height: "220"
              .text-box
                .text-box-in
                  = item.name
                .item-box-num
                  .price-box
                    = "¥#{item.price.to_s(:delimited)}"
                    .price-in
                  .num-box
                    .nice
                      = fa_icon 'heart'
                    .num
                      10
    .another-brand
      .another-brand-in
        ニューバランスのスニーカー その他の商品
    .another-brand-image
      .another-brand-image-box
        .another-image-box-in
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
        .another-image-box-in
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
          .image-box
            .image-box-in
              .image-box-in-ph
            .text-box
              .text-box-in
                NEW BALANCE MRL996AN ネイビー NB
              .item-box-num
                .price-box
                  ¥10,900
                  .price-in
                .num-box
                  .nice
                    = fa_icon 'heart'
                  .num
                    8
.bread-crumbs
  .bread-crumbs-in
    .left-bar
      .home
        メルカリ
      .icon
        >
    .right-bar
      .item
        ニューバランス New Balance 1400 26.5cm ホワイト
.footer
  = render "shared/footer"